# Generated by Django 4.1.2 on 2022-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=10)),
                ('time', models.TimeField(max_length=10)),
                ('branch', models.CharField(choices=[('select branch', 'select branch'), ('hyderabad', 'Hyderabad'), ('vijayawada', 'Vijayawada'), ('vishakhapatnam', 'Vishakhapatnam')], default='select branch', max_length=20)),
                ('people', models.IntegerField(choices=[(0, 'select persons'), (1, '1 person'), (2, '2 persons'), (3, '3 persons'), (4, '4 persons'), (5, '5 persons'), (6, '6 persons')], default='select persons')),
            ],
        ),
    ]
