# Generated by Django 4.1.2 on 2022-12-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtable',
            old_name='date',
            new_name='sdate',
        ),
        migrations.RenameField(
            model_name='addtable',
            old_name='time',
            new_name='stime',
        ),
    ]
